app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/gethomepage/homepage
            tag: v0.10.9
  service:
    main:
      ports:
        http:
          port: 3000
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host home.havki.no
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - hosts:
            - *host
          secretName: homepage-tls-certificate
  persistence:
    config:
      enabled: true
      type: configMap
      name: homepage-config
      globalMounts:
        - path: /app/config/settings.yaml
          subPath: settings.yaml
        - path: /app/config/widgets.yaml
          subPath: widgets.yaml
        - path: /app/config/services.yaml
          subPath: services.yaml
        - path: /app/config/bookmarks.yaml
          subPath: bookmarks.yaml
  configMaps:
    config:
      enabled: true
      data:
        settings.yaml: |
          background: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
          cardBlur: md
          theme: dark
          headerStyle: boxed
          hideVersion: true
        widgets.yaml: |
          - search:
              provider: google
              target: _blank
        services.yaml: |
          - Popular:
            - Matrix:
                href: https://chat.havki.no
                description: Chat client
                icon: element.svg
            - Jellyfin:
                href: https://jellyfin.havki.no
                description: Media system (movies, music, etc.)
                icon: jellyfin.svg
            - Jellyseerr:
                href: https://jellyseerr.havki.no
                description: Request media
                icon: jellyseerr.svg
            - Paperless:
                href: https://paperless.havki.no
                description: Document management system
                icon: paperless.svg
          - Management:
            - Transmission:
                href: https://transmission.havki.no
                description: Bittorrent client
                icon: transmission.svg
            - Prowlarr:
                href: https://prowlarr.havki.no
                description: Indexer manager
                icon: prowlarr.svg
            - Radarr:
                href: https://radarr.havki.no
                description: Movie manager
                icon: radarr.svg
            - Sonarr:
                href: https://sonarr.havki.no
                description: TV show manager
                icon: sonarr.svg
            - Kanidm:
                href: https://auth.havki.no
                description: Identity management
                icon: https://auth.havki.no/pkg/img/logo-square.svg
          - Development:
            - Gitea:
                href: https://git.havki.no
                description: Git forge
                icon: gitea.svg
            - Woodpecker:
                href: https://ci.havki.no
                description: Continuous integration
                icon: woodpecker-ci.svg
            - ArgoCD:
                href: https://argocd.havki.no
                description: Continuous deployment
                icon: argocd.svg
            - Registry:
                href: https://registry.havki.no
                description: Container registry
                icon: docker.svg
            - Grafana:
                href: https://grafana.havki.no
                description: Observability dashboards
                icon: grafana.svg
          - Utilities:
            - Excalidraw:
                href: https://draw.havki.no
                description: Virtual whiteboard
                icon: excalidraw.svg
            - Speedtest:
                href: https://speedtest.havki.no
                description: Internal network speed test
                icon: openspeedtest.png
        bookmarks.yaml: |
          - Homelab:
            - Documentation:
              - href: https://homelab.havki.no
                icon: google-docs.svg
            - Public homelab repository:
              - href: https://github.com/shynd/homelab
                icon: github.svg
          - Managed services:
            - Cloudflare:
              - href: https://dash.cloudflare.com
                icon: cloudflare.svg
            - Terraform Cloud:
              - href: https://app.terraform.io
                icon: terraform.svg
            - Tailscale VPN:
              - href: https://login.tailscale.com/admin/machines
                icon: tailscale.svg
          - Infrastructure:
            - Router:
              - href: https://192.168.1.1
                icon: unifi.svg
            - pi-hole:
              - href: http://192.168.30.250/admin
              icon: pi-hole.svg
            - Wazuh:
              - href: https://192.168.30.52:443
                icon: wazuh.svg
          - Proxmox cluster:
            - chase.echo.lab:
              - href: https://192.168.30.30:8006
                icon: proxmox.svg
            - kudzu.echo.lab:
              - href: https://192.168.30.31:8006
                icon: proxmox.svg
            - leo.echo.lab:
              - href: https://192.168.30.32:8006
                icon: proxmox.svg
            - pbs.echo.lab:
              - href: https://192.168.30.4:8007
                icon: proxmox.svg
