guacamole:
  guacamole:
    settings:
      POSTGRES_HOSTNAME: guacamole-postgresql.guacamole.svc.cluster.local
      POSTGRES_DATABASE: guacamole
      POSTGRES_USER: guacamole
      # todo below: auto generate this as a an external secret, the service might be internal but hardcoding is still bad
      POSTGRES_PASSWORD: 'Omegalul123!' # same as below --> postgresql.auth.password
  initdb:
    enabled: true # ensure the databse gets initialized
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      hajimari.io/appName: Guacamole
      hajimari.io/icon: remote-desktop
    hosts:
      - host: &host guacamole.havki.no
        paths:
          - /
    tls:
      - secretName: guacamole-tls-certificate
        hosts:
          - *host
  postgres:
    hostname: guacamole-postgresql.guacamole.svc.cluster.local

postgresql:
  auth:
    username: guacamole
    password: 'Omegalul123!'
    database: guacamole
