guacamole:
  guacamole:
    settings:
      POSTGRES_HOSTNAME: guacamole-postgresql.guacamole.svc.cluster.local
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: &host guacamole.havki.no
        paths:
          - /
    tls:
      - hosts:
          - *host
        secretName: guacamole-tls-certificate
  postgres:
    hostname: guacamole-postgresql.guacamole.svc.cluster.local
  postgresql:
    auth:
      username: guacamole
      password: password
      database: guacamole
