all:
  vars:
    control_plane_endpoint: 192.168.1.100
    load_balancer_ip_pool:
      - 192.168.1.224/27
metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.1.110, mac: '04:0e:3c:c1:28:f5', disk: nvme0n1, network_interface: eno1}
        metal1: {ansible_host: 192.168.1.111, mac: '04:0e:3c:c1:24:ab', disk: nvme0n1, network_interface: eno1}
        metal2: {ansible_host: 192.168.1.112, mac: '04:0e:3c:c1:24:7a', disk: nvme0n1, network_interface: eno1}
#    workers:
#      hosts:
#        metal3: {ansible_host: 192.168.1.113, mac: '00:23:24:d1:f4:d6', disk: sda, network_interface: eno1}
